# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DAWN Website

description: > # this means to ignore newlines until "baseurl:"
  DAWN, the Data Analysis WorkbeNch, is an Eclipse based application 
  for scientific data analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dawnsci.org" # the base hostname & protocol for your site

permalink: pretty

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_pages"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout

plugins:
  - "jekyll-github-metadata"

# Build settings
markdown: kramdown

include: ['_pages']
kramdown:
  input: GFM
